### ISSUE TITLE
ApplicationCommandType is not exported or not part of the library

### ISSUE THREAD

**Issue by Majoramari** [Mimickal/discordjs-command-registry#13]
Module '"discord-command-registry"' has no exported member 'ApplicationCommandType'.

**Comment by Mimickal** [comment]
I ran into this myself a few days ago. Discord.js changed a detail this library was depending on (we do `export * from <package>`), so when they changed their package, `ApplicationCommandType` stopped being exported from us. This problem exists for a few other things too. I have a fix mostly-done. When I get some time to test it more thoroughly, I'll push it up and make a release.

In the mean time, you can work around this by importing `ApplicationCommandType` from `discord.js` directly.

**Comment by Mimickal** [comment]
I decided to remove forwarded types and utilities we don't modify, since they can be easily imported directly from `discord.js` in v14. This change is on npm as `discord-command-registery@3.0.0` now.
